### ISSUE TITLE
Efi not working to boot Monterey

### ISSUE THREAD

**Issue by robi62** [shreyas-shriyan/Hp-Probook-640G1-Hackintosh-OpenCore#4]
Hi I tried your efi which works great in Bigsur , but in Monterey it reboots as soon as it loads after welcome screen
Hp 640 g1 Monterey 12.3.1

**Comment by shreyas-shriyan** [comment]
Project has been updated. Please use the latest version and report any issues.

**Comment by robi62** [comment]
I dont have laptop anymore

**Comment by Sirherobrine23** [comment]
ist the same problem, i have this notebook and try install macos big sur and monterey and cannot show macos Disks, actually  have installed MacOS Cataline with this [config to opencore](https://github.com/Sirherobrine23/Opencore_HP_640_G1).
