### ISSUE TITLE
Boot stuck on apple logo

### ISSUE THREAD

**Issue by Hack645** [shreyas-shriyan/Hp-Probook-640G1-Hackintosh-OpenCore#7]
Every time I try to boot into the Mac installation disk, it doesn't work, it only brings the apple logo, nothing else but I think the problem is with the config.plist so can you help me to solve this problem. Also my laptop is HP ProBook 640 G1

**Comment by Child-Of-Neptune** [comment]
Add “-v -keepsyms debug=0x100” in your boot-arg, which can be found in NVRAM. Then you can see which part it sticks or the error description. With that we can know which part is wrong.

**Comment by Hack645** [comment]
Done it. Thanks bro 👍🏿
